version: "3.1"

services:
  verdaccio:
    restart: unless-stopped
    image: verdaccio/verdaccio
    # image: pi0neerpat/verdaccio-group-htpasswd
    container_name: "verdaccio-group-htpasswd"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - ./config:/verdaccio/conf
      - ./storage:/verdaccio/storage
      # - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge
