# https://github.com/verdaccio/verdaccio/tree/master/conf

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  # WebUI is enabled as default, if you want disable it, just uncomment this line
  title: npm.dappy.dev
  # comment out to disable gravatar support
  # gravatar: false
  # by default packages are ordercer ascendant (asc|desc)
  # sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1 # New registration is disabled

# a list of other known repositories we can talk to
# uplinks:
#   npmjs:
#     url: https://registry.npmjs.org/

packages:
  "@dappy/*":
    access: $authorized
    publish: admin
    unpublish: admin
  "**":
    access: admin
    publish: admin
    unpublish: admin

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false

# This affect the web and api (not developed yet)
#i18n:
#web: en-US

max_body_size: 100mb
